### ISSUE TITLE
"Unknown" node is back: prometheus scaper?

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2477]
I'm seeing the "unknown" node as an source of requests to all my services:

![Capture d’écran de 2020-03-03 12-35-14](https://user-images.githubusercontent.com/2153442/75772257-e1c5fa00-5d4b-11ea-8aec-3ce8073ee437.png)

(demo-mesh-arena https://github.com/jotak/demo-mesh-arena/ with prometheus configured as it was before 1.5 to scrape pods metrics)

I strongly believe this is the prometheus scraper. In the past we wrote some rules in default istio metrics adapter to ignore requests coming from user agent prometheus and kube probes for telemetry. We had a PR merged about that in Istio. This config is not relevant anymore in istio 1.5, so we must find another way to do that.

**Comment by jotak** [comment]
related: https://github.com/istio/istio/issues/21762

**Comment by jshaughn** [comment]
@jotak Note that in 1.5 Istio has introduced [very late] support for `canonical_service` and c`anonical_revision` metric labels.  These new labels deprecate the use of `app` and `version` labels.  In the very near future (probably today) I will generate a PR adding Kiali support for this change, both in metrics and the graph.  So be on the lookout mr. future reviewer :)   We should retest this issue against the new code.
 and app and version  In the near future I will have a PR

**Comment by jotak** [comment]
@jshaughn I can't wait to review this :) but i don't think it will change anything here because the canonical service is unknown too:

`istio_requests_total{app="ai",connection_security_policy="none",destination_app="ai",destination_canonical_revision="visitors",destination_canonical_service="ai",destination_principal="unknown",destination_service="ai.default.svc.cluster.local",destination_service_name="ai",destination_service_namespace="default",destination_version="visitors",destination_workload="ai-visitors",destination_workload_namespace="default",instance="172.17.0.26:15090",job="envoy-stats",namespace="default",pod_name="ai-visitors-6f8f7fff76-rtbks",pod_template_hash="6f8f7fff76",project="mesh-arena",reporter="destination",request_protocol="http",response_code="200",response_flags="-",security_istio_io_tlsMode="istio",service_istio_io_canonical_name="ai",service_istio_io_canonical_revision="visitors",source_app="unknown",source_canonical_revision="latest",source_canonical_service="unknown",source_principal="unknown",source_version="unknown",source_workload="unknown",source_workload_namespace="unknown",version="visitors",vm="openj9"}`

**Comment by jshaughn** [comment]
yup, good point.

**Comment by jshaughn** [comment]
Reading trhough the Istio issue it seems they have accepted it as a regression and targeted for as early as Istio 1.5.1.

**Comment by lucasponce** [comment]
I'm reading the comments just to update the issue.
Is there any action on this issue ?

**Comment by jotak** [comment]
That should be tested against the istio 1.6 RC. I haven't tried it yet, focused on other tasks...

**Comment by jshaughn** [comment]
I think this should now be resolved in both 1.5 and 1.6.   Although it's not in the desciption I think this was happening only in CNI environments, like OpenShift.   The fix they put in for 1.5 did not migrate its way to 1.6 and I discovered separate issues in both HTTP and TCP metrics late last week.  The HTTP fix was put in on Thursday but the TCP issue remained.  They ended up pushing the release and getting it fixed late Friday.

Anyway, the 1.6.0-rc.2 release should have this resolved (as should the earlier 1.5 releases), but it should be tested on OpenShift/CNI.

**Comment by jshaughn** [comment]
@jotak See the above, I think this is probably resolved in 1.6.0-rc.2 but should be tested with and without CNI.

**Comment by jotak** [comment]
Just tested now: this isn't fixed, not in 1.5.4, and not in 1.6 either :-(
Prometheus scrapes still appear as "unknown".

**Comment by jotak** [comment]
@jshaughn how does it relate to CNI?

**Comment by jotak** [comment]
Hem ... now I start being confused. I'm testing with the "new way" to pull app metrics, which is using the `enablePrometheusMerge` flag (https://istio.io/docs/ops/integrations/prometheus/#option-2-metrics-merging - only in 1.6 ; "alpha" feature), and I was seeing again some telemetry originating from "unknown", but after leaving my computer a couple of hours it was gone.
I'm not sure if this "unknown" is prometheus or something different.

**Comment by jshaughn** [comment]
@jotak OK, sorry if I added to the confusion, I was attributing this to a different issue that I had encountered, where the "unknown" traffic was coming from the readiness probe.   Definitely need to keep pushing in them in the Istio issue for both the 1.5 and 1.6 z-streams.

**Comment by lucasponce** [comment]
I wonder if this problem is related to this issue:
https://github.com/istio/istio/issues/24379

**Comment by jshaughn** [comment]
@jotak Assuming this is still an issue we need to re-test when Istio 1.6.5 is released.  I wonder now if it is related to https://github.com/istio/istio/issues/24379.

**Comment by lucasponce** [comment]
Moving this issue to Sprint 43, but I wonder if it's still active.

**Comment by jshaughn** [comment]
@lucasponce Hard to know, when https://github.com/istio/istio/issues/24379 is finally resolved then it would be good to retest this one as well.

**Comment by jshaughn** [comment]
@lucasponce @jotak OK, As a result of https://github.com/istio/istio/issues/24379 Istio 1.7 fixes the default timeout for proto-sniffing but they threw their hands up wrt fixing the issue completely, deferring to https://github.com/istio/istio/issues/24998 for a final fix.  So, if the issue is still happening then the official workaround is to disable proto-sniffing (set values.pilot.enableProtocolSniffingForInbound=false and values.pilot.enableProtocolSniffingForOutbound=false).  If you actually need proto-sniffing then I don't think there is a workaround).  Either way, I don't think this is really a Kiali issue in the sense that we can do anything about the problem.  We may want to re-test on 1.7, doc the results, and close, leaving this issue as documentation.

**Comment by bianpengyuan** [comment]
FWIW, 1.5 does not have proto sniffing enabled by default, it was introduced in 1.6. This is most likely something else.

I can try to reproduce this issue with this demo app: https://github.com/jotak/demo-mesh-arena/

**Comment by jotak** [comment]
Some update here, not sure what changed / how it was fixed in Istio but I don't see the problem anymore in 1.7.
Closing.

**Comment by upodroid** [comment]
@jotak this is still an issue in 1.7.1

![image](https://user-images.githubusercontent.com/25100905/94254514-cbb59c00-ff1e-11ea-9101-edb131bc8f73.png)

```
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  134✎  4+  #    istioctl version
1 error occurred:
        * error port-forewarding into cluster-local-gateway-85568bc886-n9xsd : the server is currently unable to handle the request (get pods cluster-local-gateway-85568bc886-n9xsd:15014)


1.7.1
data plane version: 1.7.1 (30 proxies
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  134✎  4+  64  #    istioctl proxy-status
NAME                                                                CDS        LDS        EDS        RDS        ISTIOD                     VERSION
activator-68cbc9b5c7-tnttg.knative-serving                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
alertmanager-prometheus-operator-kube-p-alertmanager-0.default      SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
autoscaler-5cf649dbb-g8lct.knative-serving                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
cert-manager-79457cf5c5-8rkhs.cert-manager                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
cert-manager-cainjector-5f845bf6c7-jn6z7.cert-manager               SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
cert-manager-webhook-8484675bd8-hqsjp.cert-manager                  SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
cluster-local-gateway-85568bc886-n9xsd.istio-system                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
controller-56b9b48c6c-vjshs.cloud-run-events                        SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
controller-bc8d75cbc-jncxh.knative-serving                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
default-brokercell-ingress-6c556fb-4r2c6.cloud-run-events           SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
event-display-7lkvf-deployment-7d55f6565d-rz8gd.default             SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
eventing-controller-7558c947d-7vbq9.knative-eventing                SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
eventing-webhook-847f56845b-cw95g.knative-eventing                  SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
istio-ingressgateway-6f59657d45-xgwbc.istio-system                  SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
istio-webhook-6dd89ff45d-bn65g.knative-serving                      SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
net-certmanager-webhook-74f75674c4-zrrfl.knative-serving            SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
networking-certmanager-79dbf4b7b7-bl8n2.knative-serving             SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
pingsource-mt-adapter-84b48b94b-vnxpv.knative-eventing              SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-operator-grafana-78d5c686d5-fn9ht.default                SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-operator-kube-p-operator-b7cb676cd-pqgcd.default         SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-operator-kube-state-metrics-66b4c95cd9-hq27q.default     SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-operator-prometheus-node-exporter-fh8lm.default          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-operator-prometheus-node-exporter-wrr7h.default          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-operator-prometheus-node-exporter-wx655.default          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
prometheus-prometheus-operator-kube-p-prometheus-0.default          SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
thanos-bucket-7cb5b796c7-ndz9s.default                              SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
thanos-compact-5b584ddc57-tp6bg.default                             SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
thanos-query-7c454966b5-bg4sm.default                               SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
thanos-store-0-78ff96ff95-k2q59.default                             SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
webhook-85758f4589-b76xx.knative-serving                            SYNCED     SYNCED     SYNCED     SYNCED     istiod-f58775d55-9gz6g     1.7.1
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  134✎  4+  #    k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lucasponce** [comment]
@bianpengyuan as you can see, this issue is not just a corner case, I'm afraid more customer may have this scenario.

Thanks for reporting @upodroid.

@bianpengyuan would you mind to reopen the discussion in Istio ? 

Thanks

**Comment by jotak** [comment]
Hi @upodroid 
It looks like something different: in my initial issue, I was seeing an unknown (presumably prometheus scraper) doing requests to every single mesh workloads.

In your case there's "something" doing requests **to** prometheus. I'd imagine at first that could be users connecting to the prometheus console, but given the requests per second that seems to be high, it must be something else? Do you have any idea what it could be?

**Comment by jotak** [comment]
@upodroid actually perhaps what you see is more related to this issue: https://github.com/istio/istio/issues/24379#issuecomment-692184727 ; do you think so?

**Comment by upodroid** [comment]
I'm not sure, but envoy is logging loads of these.

```
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  134✎  5+  #    k logs prometheus-prometheus-operator-kube-p-prometheus-0 -c istio-proxy --since 30s | grep through
[2020-09-25T11:24:03.851Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 5760 7 6 "-" "Prometheus/2.18.2" "64de2fdf-3f15-4830-ae80-a505b40323c1" "10.201.64.122:9090" "10.201.64.122:9090" PassthroughCluster 10.201.66.57:37990 10.201.64.122:9090 10.201.66.57:43380 - allow_any
[2020-09-25T11:24:04.391Z] "GET /metrics/cadvisor HTTP/1.1" 200 - "-" "-" 0 101533 155 120 "-" "Prometheus/2.18.2" "d8dac55f-7c71-46fd-b7a1-029ead6286ff" "10.101.0.27:10255" "10.101.0.27:10255" PassthroughCluster 10.201.66.57:49220 10.101.0.27:10255 10.201.66.57:35216 - allow_any
[2020-09-25T11:24:04.556Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2132 3 3 "-" "Prometheus/2.18.2" "051af587-7dbf-43af-a482-be165b8725f8" "10.201.64.4:15014" "10.201.64.4:15014" PassthroughCluster 10.201.66.57:48786 10.201.64.4:15014 10.201.66.57:34790 - allow_any
[2020-09-25T11:24:04.588Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 13193 324 323 "-" "Prometheus/2.18.2" "98ff5f0e-262f-442f-a523-8783588df34d" "10.101.0.28:10255" "10.101.0.28:10255" PassthroughCluster 10.201.66.57:59144 10.101.0.28:10255 10.201.66.57:45150 - allow_any
[2020-09-25T11:24:07.313Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2132 5 4 "-" "Prometheus/2.18.2" "6c2741b9-fc5a-4393-b7c1-b87986065896" "10.201.64.63:8080" "10.201.64.63:8080" PassthroughCluster 10.201.66.57:45552 10.201.64.63:8080 10.201.66.57:59824 - allow_any
[2020-09-25T11:24:08.780Z] "POST /api/v2/alerts HTTP/1.1" 200 - "-" "-" 613 0 3 3 "-" "Prometheus/2.18.2" "f3caeac7-54eb-4f02-a656-c36032456e1a" "10.201.64.67:9093" "10.201.64.67:9093" PassthroughCluster 10.201.66.57:36948 10.201.64.67:9093 10.201.66.57:60952 - allow_any
[2020-09-25T11:24:08.855Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 5961 6 6 "-" "Prometheus/2.18.2" "2679786f-fff5-4659-87f8-ef5672223073" "10.201.64.117:10902" "10.201.64.117:10902" PassthroughCluster 10.201.66.57:56230 10.201.64.117:10902 10.201.66.57:33042 - allow_any
[2020-09-25T11:24:08.954Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 13742 578 577 "-" "Prometheus/2.18.2" "c00b3c18-0c86-42e6-bc2b-6c75194d61a8" "10.101.0.27:10255" "10.101.0.27:10255" PassthroughCluster 10.201.66.57:49220 10.101.0.27:10255 10.201.66.57:35432 - allow_any
[2020-09-25T11:24:10.284Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 4535 4 4 "-" "Prometheus/2.18.2" "ff1da771-bb38-4b8a-95f5-e45d3c4d9ebc" "10.201.64.67:9093" "10.201.64.67:9093" PassthroughCluster 10.201.66.57:36986 10.201.64.67:9093 10.201.66.57:51300 - allow_any
[2020-09-25T11:24:10.317Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 1359787 11 2 "-" "Prometheus/2.18.2" "ed4c05aa-ceb9-47c5-bc82-c8f5cb36bb83" "10.201.66.52:8080" "10.201.66.52:8080" PassthroughCluster 10.201.66.57:55686 10.201.66.52:8080 10.201.66.57:41770 - allow_any
[2020-09-25T11:24:11.806Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2134 2 2 "-" "Prometheus/2.18.2" "eb63b744-3b5e-4814-a008-63f0fd048ae4" "10.201.64.4:15014" "10.201.64.4:15014" PassthroughCluster 10.201.66.57:49038 10.201.64.4:15014 10.201.66.57:35132 - allow_any
[2020-09-25T11:24:11.977Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2972 2 2 "-" "Prometheus/2.18.2" "e2a6844f-57fc-44c2-9a3b-3191b1e7d2ab" "10.201.65.13:8383" "10.201.65.13:8383" PassthroughCluster 10.201.66.57:37300 10.201.65.13:8383 10.201.66.57:51626 - allow_any
[2020-09-25T11:24:11.984Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 5383 6 5 "-" "Prometheus/2.18.2" "159856bb-3a79-4be9-b835-9ca90ba32925" "10.201.64.118:10902" "10.201.64.118:10902" PassthroughCluster 10.201.66.57:53618 10.201.64.118:10902 10.201.66.57:58150 - allow_any
[2020-09-25T11:24:12.031Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 12841 323 323 "-" "Prometheus/2.18.2" "637af867-f7aa-46a6-bc62-add00f7748bc" "10.101.0.26:10255" "10.101.0.26:10255" PassthroughCluster 10.201.66.57:58588 10.101.0.26:10255 10.201.66.57:44682 - allow_any
[2020-09-25T11:24:14.879Z] "POST /api/v2/alerts HTTP/1.1" 200 - "-" "-" 646 0 1 1 "-" "Prometheus/2.18.2" "1b814f07-13cb-4dff-be81-a427f5cd325f" "10.201.64.67:9093" "10.201.64.67:9093" PassthroughCluster 10.201.66.57:36948 10.201.64.67:9093 10.201.66.57:60952 - allow_any
[2020-09-25T11:24:15.275Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 6146 7 5 "-" "Prometheus/2.18.2" "29129d00-5a79-489a-ab44-2ea58fec88d1" "10.201.66.5:15014" "10.201.66.5:15014" PassthroughCluster 10.201.66.57:60694 10.201.66.5:15014 10.201.66.57:46806 - allow_any
[2020-09-25T11:24:15.523Z] "GET /metrics/cadvisor HTTP/1.1" 200 - "-" "-" 0 106560 96 68 "-" "Prometheus/2.18.2" "70933c96-45f3-4c9f-aa99-90cea7b43dec" "10.101.0.26:10255" "10.101.0.26:10255" PassthroughCluster 10.201.66.57:58702 10.101.0.26:10255 10.201.66.57:44816 - allow_any
[2020-09-25T11:24:15.748Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 6146 6 5 "-" "Prometheus/2.18.2" "f2408f82-3b94-402f-9e9b-cf75ec036817" "10.201.66.5:15014" "10.201.66.5:15014" PassthroughCluster 10.201.66.57:60694 10.201.66.5:15014 10.201.66.57:46832 - allow_any
[2020-09-25T11:24:16.300Z] "GET /metrics/cadvisor HTTP/1.1" 200 - "-" "-" 0 140426 109 75 "-" "Prometheus/2.18.2" "9c615e65-a92c-49c6-9dca-9777ee30cb96" "10.101.0.28:10255" "10.101.0.28:10255" PassthroughCluster 10.201.66.57:59540 10.101.0.28:10255 10.201.66.57:45656 - allow_any
[2020-09-25T11:24:17.185Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 4532 5 5 "-" "Prometheus/2.18.2" "ed4bf72c-ad6c-402e-9f31-8f60c4c0851f" "10.201.65.12:10902" "10.201.65.12:10902" PassthroughCluster 10.201.66.57:41594 10.201.65.12:10902 10.201.66.57:55952 - allow_any
[2020-09-25T11:24:18.857Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 5770 8 7 "-" "Prometheus/2.18.2" "06d58300-05e8-42e7-a734-d82114662192" "10.201.64.122:9090" "10.201.64.122:9090" PassthroughCluster 10.201.66.57:38504 10.201.64.122:9090 10.201.66.57:43380 - allow_any
[2020-09-25T11:24:19.555Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2132 3 2 "-" "Prometheus/2.18.2" "8ceb2ec8-a4f0-409d-9ce1-8f10b7e56013" "10.201.64.4:15014" "10.201.64.4:15014" PassthroughCluster 10.201.66.57:49296 10.201.64.4:15014 10.201.66.57:34790 - allow_any
[2020-09-25T11:24:19.453Z] "GET /metrics/cadvisor HTTP/1.1" 200 - "-" "-" 0 101642 328 188 "-" "Prometheus/2.18.2" "5fb47365-a254-4add-a27d-4711b6925b99" "10.101.0.27:10255" "10.101.0.27:10255" PassthroughCluster 10.201.66.57:49730 10.101.0.27:10255 10.201.66.57:35216 - allow_any
[2020-09-25T11:24:19.589Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 13176 341 341 "-" "Prometheus/2.18.2" "50cf2ca7-88d5-4ef5-932f-838c097e71b8" "10.101.0.28:10255" "10.101.0.28:10255" PassthroughCluster 10.201.66.57:59650 10.101.0.28:10255 10.201.66.57:45150 - allow_any
[2020-09-25T11:24:20.247Z] "POST /api/v2/alerts HTTP/1.1" 200 - "-" "-" 751 0 3 2 "-" "Prometheus/2.18.2" "8d1c9c37-7bc1-4802-bad3-c184f46593a5" "10.201.64.67:9093" "10.201.64.67:9093" PassthroughCluster 10.201.66.57:36948 10.201.64.67:9093 10.201.66.57:60952 - allow_any
[2020-09-25T11:24:23.854Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 5963 6 5 "-" "Prometheus/2.18.2" "4a699321-d85e-49c1-8a62-9508634e04ab" "10.201.64.117:10902" "10.201.64.117:10902" PassthroughCluster 10.201.66.57:56744 10.201.64.117:10902 10.201.66.57:33042 - allow_any
[2020-09-25T11:24:23.954Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 13725 461 460 "-" "Prometheus/2.18.2" "e5261085-227d-4dd9-b94a-2ddf82193c83" "10.101.0.27:10255" "10.101.0.27:10255" PassthroughCluster 10.201.66.57:49730 10.101.0.27:10255 10.201.66.57:35432 - allow_any
[2020-09-25T11:24:25.009Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2976 2 2 "-" "Prometheus/2.18.2" "993f6ef8-d204-4517-b3f6-009c145d59c7" "10.201.65.13:8383" "10.201.65.13:8383" PassthroughCluster 10.201.66.57:37734 10.201.65.13:8383 10.201.66.57:52152 - allow_any
[2020-09-25T11:24:26.805Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2135 2 1 "-" "Prometheus/2.18.2" "14a539c3-5764-4b84-a2c3-b17d6840f65b" "10.201.64.4:15014" "10.201.64.4:15014" PassthroughCluster 10.201.66.57:49542 10.201.64.4:15014 10.201.66.57:35132 - allow_any
[2020-09-25T11:24:26.976Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 2969 2 1 "-" "Prometheus/2.18.2" "9b6e01d7-4755-4e9e-8aac-8ab5ecc8c122" "10.201.65.13:8383" "10.201.65.13:8383" PassthroughCluster 10.201.66.57:37734 10.201.65.13:8383 10.201.66.57:51626 - allow_any
[2020-09-25T11:24:26.984Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 5381 5 5 "-" "Prometheus/2.18.2" "81f41cd9-0b16-4fa5-baf0-1ca2bf302609" "10.201.64.118:10902" "10.201.64.118:10902" PassthroughCluster 10.201.66.57:54114 10.201.64.118:10902 10.201.66.57:58150 - allow_any
[2020-09-25T11:24:27.031Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 12845 291 290 "-" "Prometheus/2.18.2" "88b3ba27-9d81-4d81-8421-d10d4bb758c0" "10.101.0.26:10255" "10.101.0.26:10255" PassthroughCluster 10.201.66.57:59084 10.101.0.26:10255 10.201.66.57:44682 - allow_any
[2020-09-25T11:24:30.272Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 6146 4 3 "-" "Prometheus/2.18.2" "dd9ab4b6-a468-4b8f-bd85-e15f589a059e" "10.201.66.5:15014" "10.201.66.5:15014" PassthroughCluster 10.201.66.57:32946 10.201.66.5:15014 10.201.66.57:46806 - allow_any
[2020-09-25T11:24:30.523Z] "GET /metrics/cadvisor HTTP/1.1" 200 - "-" "-" 0 106452 130 102 "-" "Prometheus/2.18.2" "1bb4b622-64c1-4f6b-a644-811d6b4f1395" "10.101.0.26:10255" "10.101.0.26:10255" PassthroughCluster 10.201.66.57:59188 10.101.0.26:10255 10.201.66.57:44816 - allow_any
[2020-09-25T11:24:30.748Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 6149 4 4 "-" "Prometheus/2.18.2" "8cdac22c-0678-4450-94cf-9fb28600a180" "10.201.66.5:15014" "10.201.66.5:15014" PassthroughCluster 10.201.66.57:32946 10.201.66.5:15014 10.201.66.57:46832 - allow_any
[2020-09-25T11:24:31.300Z] "GET /metrics/cadvisor HTTP/1.1" 200 - "-" "-" 0 140748 118 82 "-" "Prometheus/2.18.2" "d2724002-0d97-4e67-a9c4-1f555c6204d0" "10.101.0.28:10255" "10.101.0.28:10255" PassthroughCluster 10.201.66.57:60038 10.101.0.28:10255 10.201.66.57:45656 - allow_any
[2020-09-25T11:24:32.186Z] "GET /metrics HTTP/1.1" 200 - "-" "-" 0 4528 4 4 "-" "Prometheus/2.18.2" "a96c2f21-e6ad-4fbf-b0ea-2cacaf202d81" "10.201.65.12:10902" "10.201.65.12:10902" PassthroughCluster 10.201.66.57:42092 10.201.65.12:10902 10.201.66.57:55952 - allow_any
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  134✎  5+  #    k get endpoints -A | grep -e 10.201.66.57 -e 10.101.0.27
default            prometheus-operated                                  10.201.66.57:9090,10.201.66.57:10901                                     3d
default            prometheus-operator-kube-p-prometheus                10.201.66.57:9090                                                        3d
default            thanos-sidecar-grpc                                  10.201.66.57:10901                                                       8d
default            thanos-sidecar-http                                  10.201.66.57:10902                                                       8d
kube-system        prometheus-operator-kube-p-kubelet                   10.101.0.26:10255,10.101.0.27:10255,10.101.0.28:10255 + 6 more...        8d
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  asml-ccoe-landing-zone  k8s   master  134✎  5+  #    
```

**Comment by upodroid** [comment]
I saw that issue and I set `protocolDetectionTimeout` to 5s and i'm still seeing it.

**Comment by jotak** [comment]
Hmm I can see `prometheus-operator-kube-p-kubelet` that is apparently not part of the mesh and could be the origin of these unknown requests.
But, by the way, is it on purpose that you have deployed the prometheus infrastructure inside the mesh? This isn't a usual pattern as far as I can tell. Anything that would connect to prometheus, and that isn't part of the mesh, would generate this kind of "unknown" telemetry unless it passes through istio gateways.

**Comment by jshaughn** [comment]
> I saw that issue and I set protocolDetectionTimeout to 5s and i'm still seeing it.

@upodroid The only way to prove whether the issue is due to https://github.com/istio/istio/issues/24379 is to completely disable proto-sniffing (this can cause other issues if you depend on server-first protocols).   See https://github.com/istio/istio/issues/24379#issuecomment-669921820 for the details on how to disable proto-sniffing.

In Istio 1.8 it is planned to make the proto-sniffing timeout infinite (see https://github.com/istio/istio/issues/24998), which will hopefully resolve 24379.  

The problem here may very well be different, I'm just passing on some information.

**Comment by upodroid** [comment]
In my case I want all the cluster traffic to be in the mesh for logging and tracing purposes. 

I'll try disabling proto-sniffing and see how the graph looks like.

That service has no selectors but there are endpoints that match the ports.

```
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  134✎  5+  #    k get endpoints prometheus-operator-kube-p-kubelet -n kube-system -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2020-09-16T14:28:42Z"
  labels:
    k8s-app: kubelet
  name: prometheus-operator-kube-p-kubelet
  namespace: kube-system
  resourceVersion: "3987614"
  selfLink: /api/v1/namespaces/kube-system/endpoints/prometheus-operator-kube-p-kubelet
  uid: 3a0b8593-c045-486c-8bc6-c4571614663d
subsets:
- addresses:
  - ip: 10.101.0.26
    targetRef:
      kind: Node
      name: gke-dev-pool-1-c92fe456-k409
      uid: fc105f86-f138-4158-ac15-11421399cd56
  - ip: 10.101.0.27
    targetRef:
      kind: Node
      name: gke-dev-pool-1-c92fe456-xk1c
      uid: 6e349fbc-4956-47c2-bba3-38e2d22605f7
  - ip: 10.101.0.28
    targetRef:
      kind: Node
      name: gke-dev-pool-1-c92fe456-6zfp
      uid: 2ec90dfb-69b6-4e69-944d-0eafaa7b803f
  ports:
  - name: http-metrics
    port: 10255
    protocol: TCP
  - name: cadvisor
    port: 4194
    protocol: TCP
  - name: https-metrics
    port: 10250
    protocol: TCP
```

I created a serviceentry for this but i still see passthroughcluster for this service.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kube-system-egress
  namespace: istio-system
spec:
  hosts:
  - prometheus-operator-kube-p-kubelet.kube-system.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: https-metrics
    number: 10250
    protocol: HTTPS
  - name: http-metrics
    number: 10255
    protocol: HTTP
  # - name: cadvisor
  #   number: 4194
  #   protocol: TCP
  resolution: DNS
```

**Comment by gadiener** [comment]
Hello everyone, I'm facing the same problem with the Datadog agent in the cluster, is there any workaround for that? 

![Screenshot 2021-03-25 at 11 54 01](https://user-images.githubusercontent.com/8479033/112463176-3591ef80-8d62-11eb-81ba-cd357161c79c.png)

**Comment by jotak** [comment]
I'm not sure how the istio team tackled [this issue](https://github.com/istio/istio/issues/21762). What would be neat, is if the sidecar processing (or at least, the telemetry part) could be bypassed based on user-agent. I don't know if that's possible, this should perhaps be reported to the istio team

**Comment by jshaughn** [comment]
+1, I think this is a telemetry issue to be pursued with Istio, Kiali is just visualizing the generated traffic metrics.  You could remove it with a graph hide expression.

**Comment by gadiener** [comment]
Thanks @jotak and @jshaughn, I added a comment on the Istio side too, let's see.

**Comment by lucasponce** [comment]
https://github.com/istio/istio/issues/21762#issuecomment-713674688
and 
https://github.com/istio/istio/issues/21762#issuecomment-807128053

So, I'm going to close it from Kiali side, we can re-open it with more information if this issues is still active in recent Istio + Kiali versions.
