### ISSUE TITLE
Some HTTP request still pending and never load (Graph, Applications, Workloads)

### ISSUE THREAD

**Issue by JuanSeBestia** [kiali/kiali#3494]
**Describe the bug**
the application keeps processing some calls indefinitely, this can happen with various APIs in various sections of the application (such as Graph, Applications, Workloads, ... etc).

I waited half an hour and the HTTP call was still pending 

reference image
<img width="1666" alt="Screen Shot 2020-12-01 at 4 46 00 PM" src="https://user-images.githubusercontent.com/7362688/100809050-4d381780-3403-11eb-945d-f315ad063b03.png">

The strangest thing is that it only happens in a productive environment, in my company has 3 types of environments (prod, staging, ephemeral env), but this can **only** be reproduced in the prod environment.

I have seen the logs in debug mode and they are not interesting at all, I will still attach them.

I don't have a clue what happens, any suggestion is welcome :)

I roll back to Kiali Operator v1.24.0 and it works as expected, but I will continue with this version for now.

**Versions used**
Kiali Operator v1.26.1
Kiali UI 1.26.0 (35e2d8b075bd5c4bcc3f315aef9e6144aad0b608)
Kiali Server v1.26.1 (0cf243d730d45cd16e254e2c8d4d2a0ac0cf5222)
Kiali Container v1.26.1
Components
Istio 1.7.4
Promtheus 2.18.2
Kubernetes v1.17.13-gke.1400

**NOTE: ** also I test it with Kiali Operator v1.25.0, Kiali Operator v1.27.0

**To Reproduce**
1. Go to 'Workloads'

**Expected behavior**
Load all the workloads

**Comment by JuanSeBestia** [comment]
Logs:
[Kiali_1_26_1.txt](https://github.com/kiali/kiali/files/5626111/Kiali_1_26_1.txt)

**Comment by jotak** [comment]
@lucasponce have you ever seen this "too old resource version" log? Looks related to the watchers.

```
W1201 21:45:46.726043       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.ConfigMap ended with: too old resource version: 37868011 (37870980)
```

Perhaps when such error occurs we need to reinitialize watchers?

@JuanSeBestia 
Does that log look related with the issue, ie. do you see it constantly when the problem appears and you don't see it in your working staging environment?

**Comment by lucasponce** [comment]
El mié., 2 dic. 2020 9:42, Joel Takvorian <notifications@github.com>
escribió:

> @lucasponce <https://github.com/lucasponce> have you ever seen this "too
> old resource version" log? Looks related to the watchers.
>
> W1201 21:45:46.726043       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.ConfigMap ended with: too old resource version: 37868011 (37870980)
>
> Perhaps when such error occurs we need to reinitialize watchers?
>

That ConfigMap error means that resource has changed and it needs a refresh
in the informer but I don't think it's related to the problem with the
/apps endpoint.

It seems some overload of the k8s api, I wonder if this problem could be
reproduced to investigate

@JuanSeBestia <https://github.com/JuanSeBestia>

**Comment by JuanSeBestia** [comment]
On staging work, as expected, this is the staging log
[kiali_staging.txt](https://github.com/kiali/kiali/files/5629693/kiali_staging.txt)

As you can see the 'error' it's happened many times, but is not the reason to not work in production

**Comment by JuanSeBestia** [comment]
@lucasponce for security I can't replicate the entire prod environment, but the staging and ephemeral environments are like a copysh of prod environment.

At this moment I don't know how to replicate it in a new environment :(

**Comment by lucasponce** [comment]
Thanks @JuanSeBestia. A couple of comments that may help to debug the issue and understand the root cause.
When it happens again, if you re-start the Kiali pod, does the problem mitigates ? How much time from a pod restart until it gets this problem again ? Can you show some info about pod resources on your production environment ?

**Comment by JuanSeBestia** [comment]
The problem happens since the pod is started (all the time), the pod turns zombie if I leave the screen open after hours (maybe it is a problem with the browser when handling so many open requests)

resources production:
``` bash
$kubectl top pods kiali-59b7488fcb-4fhlc
NAME                     CPU(cores)   MEMORY(bytes)   
kiali-59b7488fcb-4fhlc   6m           94Mi   
```

resources staging:
```
$kubectl top pods kiali-ffb554679-4q5sq
NAME                    CPU(cores)   MEMORY(bytes)   
kiali-ffb554679-4q5sq   25m          127Mi           
```
Don't hesitate to request more info :)

**Comment by lucasponce** [comment]
> The problem happens since the pod is started (all the time), the pod turns zombie if I leave the screen open after hours (maybe it is a problem with the browser when handling so many open requests)

That's a good info, so, if you restart the browser, the problem changes ?

**Comment by JuanSeBestia** [comment]
Nope, try to request again the information, and the request still pending

To clarify, the problem is not fixed, neither by restarting the browser(Chrome/Brave/Safari), nor by restarting the pod, nor by reinstalling the deployment, nor by resetting the Kiali-CR, nor by reinstalling the Kiali-Operator release, nor by restarting my laptop :v

**Comment by lucasponce** [comment]
> To clarify, the problem is not fixed, neither by restarting the browser(Chrome/Brave/Safari), nor by restarting the pod, nor by reinstalling the deployment, nor by resetting the Kiali-CR, nor by reinstalling the Kiali-Operator release, nor by restarting my laptop

Certainly it's weird.

So, to confirm, problem is still happening in prod, but not in dev/staging scenarios which if I'm not wrong are identical, isn't it ?

Can you think in any difference between prod and staging that may be it's impacting here ?

I mean Kiali is failing always, since first time was installed in that env, or it was a degradation of the service ?

**Comment by jshaughn** [comment]
It does seem like there could be an environmental factor in play.   Have you tried taking Kiali out of the equation to see if any other tooling suffers from load or networking issues?   Maybe you could try Istio's grafana dashboard, or the prometheus or jaeger console directly?

**Comment by JuanSeBestia** [comment]
Kiali started to fail since it was updated in prod environment.

At this moment I cannot find a difference between the environments that should impact

**Comment by JuanSeBestia** [comment]
@jshaughn 
Prometheus Web console: OK
Jaeger Web console: OK
Istio's grafana dashboard: stable metrics

Also, I tried with Istio's add-on Prometheus and my custom Prometheus and with both has the same behavior

**Comment by JuanSeBestia** [comment]
I disable Jaeger and Grafana as external components in Kiali, and Kiali still have the same behavior 

```
external_services:
    grafana:
      enabled: false
      in_cluster_url: 'http://prometheus-grafana.observability:80'
      url: 'http://my-grafa-porforward:3000'
   tracing:
      enabled: false
      in_cluster_url: 'http://jaeger-query.observability:16686'
      namespace_selector: true
      url: 'http://my-jaeger-portforward-UI'
      whitelist_istio_system:
        - jaeger-query
        - istio-ingressgateway
...
```

**Comment by JuanSeBestia** [comment]
FYI: If I change the Prometheus url with bad configurations, it put an error of connection on logs, but Kiali still have the same behavior

Logs:
``` log
2020-12-02T16:03:31.883952205Z E1202 16:03:31.883758       1 config.go:135] Failed to fetch Prometheus configuration: Get "http://kps-prometheus-bad-url.observability:9090/api/v1/status/config": dial tcp: lookup kps-prometheus-bad-url.observability on 10.1.0.10:53: no such host
2020-12-02T16:03:31.890398805Z E1202 16:03:31.890193       1 config.go:135] Failed to fetch Prometheus flags: Get "http://kps-prometheus-bad-url.observability:9090/api/v1/status/flags": dial tcp: lookup kps-prometheus-bad-url.observability on 10.1.0.10:53: no such host
```
Kiali-CR
``` yaml
prometheus:
     component_status:
        app_label: prometheus
        is_core: true
        namespace: observability
      custom_metrics_url: 'http://kps-prometheus-bad-url.observability:9090'
      url: 'http://kps-prometheus-bad-url.observability:9090'
```

![image](https://user-images.githubusercontent.com/7362688/100898368-b022c080-348e-11eb-83e3-b3b0a696a97b.png)

**Comment by JuanSeBestia** [comment]
^  Could it means that might be Istio, Kiali or another thing?

**Comment by jshaughn** [comment]
If prometheus is unreachable and you still see this behavior it would seem to mean that the issue is with underlying Kiali interaction with the k8s API, or possibly with Kiali UI and Kiali server interaction.

**Comment by JuanSeBestia** [comment]
FYI: Kiali can get de namesapces 
![image](https://user-images.githubusercontent.com/7362688/100918233-38f92680-34a6-11eb-9f68-454cd7df0d82.png)

**Comment by lucasponce** [comment]
I wonder if you can perform another debug test:

- Try to disable the Kubernetes Cache (from the operator config and/or
configmap).

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L636

Note, it's expected to be slow but perhaps it can help to understand this
problem.

If it works well in the dev/staging environment but not in production
perhaps there is some security constraint that we are not considering and
it's affecting this.

**Comment by JuanSeBestia** [comment]
@lucasponce Congratulations you hit the jackpot!

I configured what you mentioned about the kubernetes cache and it worked
Version Kiali-Operator & Kiali 1.26.1
Logs file
[kiali_1_26_1_cache_disable.txt](https://github.com/kiali/kiali/files/5631836/kiali_1_26_1_cache_disable.txt)
Resources

``` bash
k top pods kiali-6ccfcb9ddf-2g8h5                  
NAME                     CPU(cores)   MEMORY(bytes)   
kiali-6ccfcb9ddf-2g8h5   5m           76Mi     
```
![image](https://user-images.githubusercontent.com/7362688/100927292-b165e480-34b2-11eb-9d81-3d5698dbcb47.png)

**Comment by jshaughn** [comment]
@JuanSeBestia Thanks for the fast turnaround on debugging requests.  Without the cache enabled your performance may be slow, but hopefully you can proceed while we investigate the issue.  Lucas is in Europe TZ and will likely follow up tomorrow.

**Comment by JuanSeBestia** [comment]
Unfortunately, Kiali versions 1.25.0 1.26.0 and 1.27.0 configured with `kubernetes_config.cache_enabled: false` has the same bug that was reported in other versions, see more in https://github.com/kiali/kiali/issues/3318

**Comment by lucasponce** [comment]
Thanks @JuanSeBestia, definitely that step shows more info.

It's pretty strange that caching doesn't work in prod but in staging/dev environments, so I suspect the problem was in how the operator/kiali was migrated.

If there was some missing role or a bad serviceaccount applied perhaps some API doesn't have rights and instead to fail with a 403 error it hangs due some restriction in the prod env.

So, now goal is to understand that this env is failing, would you mind to post the serviceaccount and serviceaccountbinding of kiali ?

Specifically I'm interested to understand which roles are being applied.

Thanks !

**Comment by JuanSeBestia** [comment]
SA
``` yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kiali-service-account
  namespace: observability
  selfLink: /api/v1/namespaces/observability/serviceaccounts/kiali-service-account
  uid: 5247e67b-e93d-460d-8b5a-ab9229d8bb8a
  resourceVersion: '39077646'
  creationTimestamp: '2020-12-01T15:39:32Z'
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.27.0
    version: v1.27.0
  ownerReferences:
    - apiVersion: kiali.io/v1alpha1
      kind: Kiali
      name: kiali
      uid: 2d332536-15d3-4ece-85bd-0962a6f0b6ef
secrets:
  - name: kiali-service-account-token-g6gfv

```
SA Operator

```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kiali-operator
  namespace: operators
  selfLink: /api/v1/namespaces/operators/serviceaccounts/kiali-operator
  uid: 8ba17140-008d-4935-b31a-ef63aac2d45f
  resourceVersion: '39077297'
  creationTimestamp: '2020-12-01T15:34:04Z'
  labels:
    app: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/part-of: kiali-operator
    app.kubernetes.io/version: v1.27.0
    helm.sh/chart: kiali-operator-1.27.0
    version: v1.27.0
  annotations:
    helm.fluxcd.io/antecedent: 'operators:helmrelease/kiali-operator'
secrets:
  - name: kiali-operator-token-h8xw2

```

ClusterRole Kiali:

``` yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kiali
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kiali
  uid: 044dc80d-cbb5-448e-8365-f6c849c6bd92
  resourceVersion: '39077668'
  creationTimestamp: '2020-12-01T15:39:34Z'
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.27.0
    version: v1.27.0
  annotations:
    operator-sdk/primary-resource: observability/kiali
    operator-sdk/primary-resource-type: Kiali.kiali.io
rules:
  - verbs:
      - get
      - list
      - patch
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - pods
      - pods/log
      - pods/proxy
      - replicationcontrollers
      - services
  - verbs:
      - get
      - list
      - patch
      - watch
    apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - get
      - list
      - patch
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
    apiGroups:
      - networking.istio.io
      - security.istio.io
    resources:
      - '*'
  - verbs:
      - get
      - list
    apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
    apiGroups:
      - iter8.tools
    resources:
      - experiments

```

ClusterRole Operator

``` yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kiali-operator
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kiali-operator
  uid: 0441db12-18d8-4dee-9d6b-1e19ce33a16b
  resourceVersion: '39077298'
  creationTimestamp: '2020-12-01T15:34:04Z'
  labels:
    app: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/part-of: kiali-operator
    app.kubernetes.io/version: v1.27.0
    helm.sh/chart: kiali-operator-1.27.0
    version: v1.27.0
  annotations:
    helm.fluxcd.io/antecedent: 'operators:helmrelease/kiali-operator'
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - serviceaccounts
      - services
      - services/finalizers
  - verbs:
      - get
      - list
      - patch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - create
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - kiali-signing-key
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
  - verbs:
      - create
      - get
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - update
    apiGroups:
      - apps
    resources:
      - deployments/finalizers
    resourceNames:
      - kiali-operator
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - kiali.io
    resources:
      - '*'
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
  - verbs:
      - list
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
  - verbs:
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
    resourceNames:
      - kube-apiserver
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - pods
      - pods/log
      - pods/proxy
      - replicationcontrollers
      - services
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - networking.istio.io
      - security.istio.io
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - list
    apiGroups:
      - monitoring.kiali.io
    resources:
      - monitoringdashboards
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - iter8.tools
    resources:
      - experiments

```

RoleBinding Kiali

``` yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kiali
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kiali
  uid: 32962348-1866-4092-8506-408ccbc5a9f0
  resourceVersion: '39077684'
  creationTimestamp: '2020-12-01T15:39:35Z'
  labels:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.27.0
    version: v1.27.0
  annotations:
    operator-sdk/primary-resource: observability/kiali
    operator-sdk/primary-resource-type: Kiali.kiali.io
subjects:
  - kind: ServiceAccount
    name: kiali-service-account
    namespace: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali

```

**Comment by lucasponce** [comment]
Thanks @JuanSeBestia the config looks ok.

I wonder if you could check if the config in dev/stage envs is similar  (that again, we take assumption that three environments are identical but prod is the one is not working).

Also, in the Kiali operator, you have the field "accessible_namespaces" set to "**" as described in [1] (well, I shouldn't affect if you have the ClusterRoles but just collecting more info in case it can show something different).

Honestly I don't understand why the cache mechanism doesn't work in prod env, but it works in dev/stage ones if they are sharing same configuration.

If we can reproduce the problem in an isolated problem I'm afraid we'd need to perform some queries from the Kiali pod to see if we spot a difference.

I'd recommend to open a shell from Kiali pod:

```
export KIALI_POD=$(kubectl get pod -l app=kiali -o jsonpath='{.items..metadata.name}' -n istio-system)
kubectl exec --stdin --tty ${KIALI_POD} -n istio-system -- /bin/bash
```

And try to query the Kubernetes API simulating what a cache does:

```
# Inside a Pod
KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

# Query all pods for a given namespace i.e. istio-system
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/istio-system/pods

# Watch all pods for a given namespace i.e. istio-system
# This query doesn't return, it's always open and sending updates, perhaps one of these queries is not working on prod env, basically the caching mechanism use this api to update deltas between a local cache and the kubernetes api

curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/istio-system/pods?watch=1

# If kubernetes API works well, let's try to test the Istio CRDs

# Watch for VirtualServices on a given namespace
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices?watch=1
```

Feel free to change the objects to query and/or namespaces to see if you identify any difference betwen prod and dev/stage envs.

If Kiali works well in those and caching is what is failing the problem should be related to this in some way.

But I don't have more ideas, if you could reproduce the issue I'd be very interested to study locally to understand it (and fix it).

[1] https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L172

**Comment by JuanSeBestia** [comment]
I finished testing all the commands you gave me to execute it within the Kiali pod, to test the ones that were waiting for changes, I made some modifications to the files that they were looking at respectively (pods, virtualservices), in both cases it showed updates.

In all cases, it worked as expected.

I can tell you that the prod environment has fewer namespaces and different names, but as you mention  "accessible_namespaces" had "**" configured, so it mustn't be the problem

**Comment by lucasponce** [comment]
@JuanSeBestia thanks a lot for the time put on debugging this.
It's odd, I'll try to reproduce locally but I'm afraid I'm missing something to understand why that prod doesn't work but the others have no problems.

I guess you commented before, the authentication method is similar in all three environments ?

**Comment by JuanSeBestia** [comment]
The configuration of Kiali-Operator and Kiali is totally the same in all envs :(

**Comment by jdartigalongue** [comment]
I have been running into the exact same issue and setting `cache_enabled` to false worked for me too. 
Private GKE cluster version 1.16.15-gke.4300

**Comment by jshaughn** [comment]
@lucasponce Adding this to the sprint backlog and assigning you as I believe you are looking into this area.

**Comment by camelpunch** [comment]
Spent today thinking I'd misconfigured Prometheus. Disabled Kubernetes caching and graphs suddenly appeared! Only found this issue after arbitrary changes in the Kiali config led me to try the caches.

This is also on a private GKE cluster, version 1.17.14-gke.400. Istio 1.8.1. Installed Kiali 1.28.1 via Kiali Operator, which was installed with the Helm chart.

**Comment by jshaughn** [comment]
@camelpunch Thanks for reporting.

**Comment by koalaty-code** [comment]
We're troubleshooting similar issues with Kiali as well. 

Kiali version: v1.28.1
Istio version: v1.6.14

We recently completed upgrading Istio from 1.5 to 1.6 utilizing a canary revision of the control plane. With the upgrade, we configured Kiali to point to our own Prometheus instance and tore down the Prometheus instance bundled with Istio 1.5. After disabling Prometheus in the Istio deployment, we started to encounter issues with Kiali similar to what is reported in this issue; pending requests that never complete or are terminated with `response_flags=UC` in our ingress gateway `istio-proxy` logs.

We tried several different configuration options for Kiali with little success. Unrelated to the issue reported here, configuring Kiali to point to a Prometheus instance outside of the default Istio namespace is ambiguous and redundant:

- Update the Prometheus namespace under `istio_component_namespaces.prometheus`
- Update the URL for Prometheus under `external_services.prometheus.url`
- Update the namespace for Prometheus under `external_services.prometheus.component_status.namespace`
- Update the URL for Prometheus under `external_services.custom_dashboard.prometheus.url`

We have had inconsistent results after setting `kubernetes_config.cache_enabled=false`. With the same configuration, we sporadically see the following behavior:

- Inability to load `Istio Config` for selected namespaces
- Inability to load `Workloads`, `Applications`, or `Graph` for selected namespaces

Throughout troubleshooting, there have been minimal logs from kiali-server providing any insight into the underlying errors (even with TRACE log_level).

Here is our current Kiali configuration which is resulting in indeterministic behavior between environments (we re-enabled Prometheus in our Istio deployment):

```yaml
    istio_namespace: istio-system
    istio_component_namespaces:
      prometheus: istio-system
    server:
      port: 20001
    kubernetes_config:
      cache_enabled: false
    external_services:
      istio:
        component_status:
          components:
            - app_label: istiod
              is_core: true
            - app_label: istio-ingressgateway
              is_core: true
            - app_label: istio-ilbgateway
              is_core: true
        config_map_name: istio-1-6
        url_service_version: http://istiod-1-6:15014/version
      grafana:
        enabled: true
        is_core_component: false
        url: https://grafana.XXX.XXX
        auth:
          password: secret:kiali:grafanaPassword
      tracing:
        url: https://jaeger.XXX.XXX
      prometheus:
        url: http://prometheus.istio-system.svc:9090
        component_status:
          namespace: istio-system
      custom_dashboards:
        prometheus:
          url: http://prometheus.istio-system.svc:9090
    auth:
      strategy: anonymous
    extensions:
      threescale:
        enabled: false
```

**Comment by jshaughn** [comment]
@koalaty-code, thanks for reporting.  Hopefully these pain points will get some resolution in the next release.

**Comment by koalaty-code** [comment]
@jshaughn, is there an ETA on the next release? Also, will the next release be tested with Istio 1.6? The installation guide only specifies to use >= 1.18.1 for Istio 1.6 which implies any newer release will be compatible with Istio 1.6.

**Comment by jshaughn** [comment]
@koalaty-code Kiali is released every 3 weeks but we're skipping a release for the holidays.  Next scheduled release is set to be 1.29 on January 22.   1.29 should be compatible with Istio 1.6 as long as you are using Telemetry V2 (not mixer).

**Comment by kevin-shelaga** [comment]
Jumping in to add regular release channel 1.17.14-gke.400 for GKE has the described issue but, rapid release channel 1.18.12-gke.1201 appear to at least finish loading with some or partially missing info in the ui.

**Comment by bougyman** [comment]
This is also affecting us on 1.17.14-gke.400

**Comment by lucasponce** [comment]
Just an update on the issue, as it seems affects to several folks.

I couldn't reproduce completely locally but I could get some odd behaviour that sounded related to the issues people are having.

It seems Kiali was using an old kubernetes/client-go+apimachinery setup that is being reviewed and tested on PR #3579

First low level investigations seem that queryies to the backend are working as expected:

![image](https://user-images.githubusercontent.com/1662329/104612836-e4d98880-5686-11eb-97f5-3f97a079deda.png)

But if some folk of the thread could reproduce the error ina constant way, I'd like to try to setup a similar env to validate.

Thanks

**Comment by lucasponce** [comment]
I'm going to keep the issue open in Sprint 52 in case there are some side effect or additional task to address, but I think when Kiali v1.29 is released, it should fix this.

**Comment by lucasponce** [comment]
cc @JuanSeBestia @bougyman @kevin-shelaga @koalaty-code @camelpunch 

Kiali v1.29.0 has been released and with updated client-go versions.

Let us know if you could have a chance to test and check if the problem is gone or if has a different result.

Thanks a lot for the feedback and time to help us to work on this issue.

**Comment by kevin-shelaga** [comment]
@lucasponce the issue persists for me with v1.29.0 unfortunately :(

**Comment by lucasponce** [comment]
Thanks for testing @kevin-shelaga. Can you point me the Kubernetes (flavor) version and Istio version.
Next step from my side is to see if I can recreate the very same environment you are seeing the bug.

**Comment by kevin-shelaga** [comment]
@lucasponce 

istio: 1.8.2
kiali: v1.29.0
k8s: 1.17.14-gke.1200

I can try with a fresh cluster and the istio demo apps, but so far I have 3 clusters all with a fresh istio and kiali install, all with the same issue. I will try a fresh setup and report back.

The workaround for now is:

```yml
     kubernetes_config:
       cache_enabled: false
```

**Comment by lucasponce** [comment]
Thanks, I'll post my findings

**Comment by lucasponce** [comment]
Ok, this is my test environment:

```
$ kubectl get nodes
NAME                                                  STATUS   ROLES    AGE   VERSION
gke-trusty-acre-302914-1-default-pool-e2bf4f7e-399c   Ready    <none>   49m   v1.17.14-gke.1200
gke-trusty-acre-302914-1-default-pool-e2bf4f7e-fl38   Ready    <none>   49m   v1.17.14-gke.1200
gke-trusty-acre-302914-1-default-pool-e2bf4f7e-jfz1   Ready    <none>   49m   v1.17.14-gke.1200
gke-trusty-acre-302914-1-default-pool-e2bf4f7e-l9g8   Ready    <none>   49m   v1.17.14-gke.1200
```

With Istio 1.8.2 and Kiali v1.29.0.

The only difference perhaps it's the networking, I didn't create any DNS, just a local entry in my local desktop on the /etc/hosts pointing to the cluster ip:

```
35.235.78.160 bookinfo.lucas-cluster.org
35.235.78.160 kiali.lucas-cluster.org
```

I have bookinfo + kiali demo apps:

![image](https://user-images.githubusercontent.com/1662329/105867230-235f3380-5ff5-11eb-868f-4b468dec0452.png)

And Kiali logs show like:

```
$ kubectl logs -f -l app=kiali -n istio-system
2021-01-26T15:32:43Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:32:51Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:32:51Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:01Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:03Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:06Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:33Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:38Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:45Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
2021-01-26T15:33:48Z ERR container istio-proxy is not valid for pod kiali-646976756d-96pn4
```

Note that error is unrelated, as I generated that line when visualizing Kiali's workload logs from Kiali UI.

@kevin-shelaga did you get the same error after some time, or just in seconds with the new Kiali v1.29 version ?

I mean, the only piece that I see different here it's the networking I guess.

**Comment by kevin-shelaga** [comment]
@lucasponce I am having difficulty replicating the issue in a fresh cluster, at this point im not sure if its related to workloads in my 3 other clusters or something with helm delete/helm install. I am hesitant to setup up a fresh cluster with my workloads but may need to.

**Comment by lucasponce** [comment]
> @lucasponce I am having difficulty replicating the issue in a fresh cluster, at this point im not sure if its related to workloads in my 3 other clusters or something with helm delete/helm install. I am hesitant to setup up a fresh cluster with my workloads but may need to.

Thanks @kevin-shelaga for the time and help on testing this.

Not sure if I can progress too much from here, I've left a note in the Istio / Kiali slack to see if there are more people that may have feedback.

As soon as we have a new data that may help us to reproduce we'll try to provide a workaround (but we expect that the v1.29.0 should be work enough).

**Comment by Miles-Ahead-Digital** [comment]
I run into the same problem (although it worked before). I could not find the reason so far.

 These URLs have (suddenly) a very long response in kiali dashboards which causes the UI to crash (due to too many open sockets):
http://localhost:20001/kiali/api/namespaces/<>/apps
http://localhost:20001/kiali/api/namespaces/<>/workloads

Once I disabled the caching in the kiali config map it worked again.
Let uns know which combination is worth to test again (kubernetes / istio / kiali)

**Comment by lucasponce** [comment]
Thanks @Miles-Ahead-Digital, are you using GKE + Istio 1.8.2 + Kiali v1.29.0 ?

Kiali v1.29.0 has been upgraded and potential problems due the internal kubernetes/client-go indexer has been tested in other platforms without being able to reproduce it.

Could you add more info into the scenario that it crashed ? Something you can get with a demo (bookinfo) or similar ?

Just also to find some additional data that can help us to reach the same point you are.

And thanks a lot for the time adding info on this issue, we are actively trying to get a similar scenario to understand the problem and investigate a fix.

**Comment by MrBlaise** [comment]
Hey! I have the same problem on multiple clusters as well using istio 1.8.1 and Kiali 1.26 or later. I've installed kiali using the script provided by istio and also using the official helm chart by Kiali and the issue is the same. Nothing really loads, the graphs are empty workloads are not showing up etc.

The only things I see after I enable debug log:

```
2021-02-01T08:32:00Z INF Kiali: Version: v1.29.0, Commit: a86a8fcffeb002d35fc0964dfd728958295b8387

2021-02-01T08:32:00Z DBG Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml]
2021-02-01T08:32:00Z DBG Reading YAML config from [/kiali-configuration/config.yaml]
2021-02-01T08:32:00Z INF Using authentication strategy [anonymous]
2021-02-01T08:32:00Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2021-02-01T08:32:00Z INF Kiali: Console version: 1.29.0
2021-02-01T08:32:00Z INF Updating base URL in index.html with [/kiali]
2021-02-01T08:32:00Z DBG Base URL has been updated to [<base href="/kiali/"]
2021-02-01T08:32:00Z INF Generating env.js from config
2021-02-01T08:32:00Z DBG The content of /opt/kiali/console/env.js will be:
window.HISTORY_MODE='browser';
window.WEB_ROOT='/kiali';

2021-02-01T08:32:00Z INF Server endpoint will start at [:20001/kiali]
2021-02-01T08:32:00Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-02-01T08:32:00Z INF Starting Metrics Server on [:9090]
2021-02-01T08:37:52Z DBG Detected Istio version [1.8.1-806fb24bc121bf93ea06f6a38b7ccb3d78d1f326-Clean]
2021-02-01T08:37:52Z INF [Prom Cache] Enabled
2021-02-01T08:37:52Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T08:37:52Z INF Kiali Cache is active for namespaces [.*]
2021-02-01T08:37:52Z DBG Rest perf config QPS: 175.000000 Burst: 200

2021-02-01T08:37:53Z INF Waiting for Kiali cache for [namespace: default] to sync
2021-02-01T08:37:53Z INF Kiali cache for [namespace: default] started
2021-02-01T08:38:53Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: my-pod-v1-b545b6478-ns678]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
```

When I change the kiali version to 1.20 everything works well and fast.

**Comment by lucasponce** [comment]
Thanks @MrBlaise 

Let me ask you some details to see if I can get the same error:
- Which version of k8s cluster are you using ?
- How many namespaces does it contain ?
- Could you recreate the error at the first time you populate a cluster ? Or this happens with a long running cluster ?

The log is insteresting, the last warning may show some light in what is happening here:
```
2021-02-01T08:38:53Z WRN GetPodProxyStatus is failing for [namespace: default] [pod: my-pod-v1-b545b6478-ns678]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
```
It seems it can be also related to https://github.com/kiali/kiali/issues/3605 which also is enabled/disabled with caching as well.

So, we hope to have another version in kiali 1.29.x where we expect to backport a fix when this problem is solved.

Again, thanks again for all the help in the investigation on this.

**Comment by MrBlaise** [comment]
@lucasponce I've updated my original comment with some extra information. Thanks!

**Comment by MrBlaise** [comment]
> @lucasponce I've updated my original comment with some extra information. Thanks!

I saw that issue as well and I had two istiod instances because in my config I've enabled autoscaling. However I scaled it back to only 1 istiod instance but that didn't help either.

**Comment by lucasponce** [comment]
@MrBlaise I'd ask you a favor.
If possible, would you mind to install any of the demos in your cluster, to see if the problem is still present there ?
Bookinfo or the Kiali demos https://github.com/kiali/demos may help.

I ask this because I couldn't reproduce it with similar versions and I would like at least to reach at that point that I can create a cluster with same error (if demos app don't fail, perhaps that's new info to investigate if workloads have something in common, I guess those should fail as well).

**Comment by MrBlaise** [comment]
> @MrBlaise I'd ask you a favor.
> If possible, would you mind to install any of the demos in your cluster, to see if the problem is still present there ?
> Bookinfo or the Kiali demos https://github.com/kiali/demos may help.
> 
> I ask this because I couldn't reproduce it with similar versions and I would like at least to reach at that point that I can create a cluster with same error (if demos app don't fail, perhaps that's new info to investigate if workloads have something in common, I guess those should fail as well).

I've installed this now: https://github.com/kiali/demos/tree/master/electronic-shop. Sadly that also didn't load at all (using kiali 1.29 with caching enabled)

Once I disable caching everything including the electronic shop loads instantly.

**Comment by lucasponce** [comment]
> Once I disable caching everything including the electronic shop loads instantly.

Ok, thanks, so, that confirms that problem is still there for any workload.

Just to confirm, you installed istio with the operator method [1].

So, any special step I should take into consideration to have a similar environment as you tested ?

Comparing envs people have reported with my test one, main different is that I used the demo profile, I'd like to discard if it's something related on the config setup.

[1] https://istio.io/latest/docs/setup/install/operator/

**Comment by MrBlaise** [comment]
> > Once I disable caching everything including the electronic shop loads instantly.
> 
> Ok, thanks, so, that confirms that problem is still there for any workload.
> 
> Just to confirm, you installed istio with the operator method [1].
> 
> So, any special step I should take into consideration to have a similar environment as you tested ?
> 
> Comparing envs people have reported with my test one, main different is that I used the demo profile, I'd like to discard if it's something related on the config setup.
> 
> [1] https://istio.io/latest/docs/setup/install/operator/

Yes I've installed with the operator here is my config:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        service:
          loadBalancerIP: REDACTED
      name: istio-ingressgateway
  profile: default
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
    global:
      proxy:
        holdApplicationUntilProxyStarts: true
        tracer: datadog
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 1
      autoscaleMin: 1
      traceSampling: 100
 ```

**Comment by lucasponce** [comment]
Thanks @MrBlaise !
I have another suspect/test if you have time.

I wonder if you could narrow the number of namespaces that Kiali can access but with cache enabled.
But default Kiali I guess is configured to see all, but I'd like to see if problem happens on every namespace or just trying to fetch a cache for all of them.

So, if you could re-install kiali with "accessible_namespaces" flag pointing to some app namespaces but with cache enabled:

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L176

if you like, you could try with the electronic-shop one.

Again, I know this is time consuming, thanks a lot for your help.

**Comment by MrBlaise** [comment]
@lucasponce I've reinstalled the electronic-shope app and started kiali like this:

```
helm install \
  --namespace istio-system \
  --set auth.strategy="anonymous" \
  --set deployment.logger.log_level="debug" \
  --set kubernetes_config.cache_enabled="true" \
  --set deployment.accessible_namespaces={"electronic-shop"} \
  --repo https://kiali.org/helm-charts \
  kiali-server \
  kiali-server
```

The problem is still there, nothing loads (keeps loading forever) :/

**Comment by lucasponce** [comment]
> The problem is still there, nothing loads (keeps loading forever) :/

Could you attach the log in this last try ?

Thanks for confirming, I'll keep investigating.

**Comment by MrBlaise** [comment]
> > The problem is still there, nothing loads (keeps loading forever) :/
> 
> Could you attach the log in this last try ?
> 
> Thanks for confirming, I'll keep investigating.

Logs
```
2021-02-01T09:56:21Z INF Kiali: Version: v1.29.0, Commit: a86a8fcffeb002d35fc0964dfd728958295b8387

2021-02-01T09:56:21Z DBG Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml]
2021-02-01T09:56:21Z DBG Reading YAML config from [/kiali-configuration/config.yaml]
2021-02-01T09:56:21Z INF Using authentication strategy [anonymous]
2021-02-01T09:56:21Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2021-02-01T09:56:21Z INF Kiali: Console version: 1.29.0
2021-02-01T09:56:21Z INF Updating base URL in index.html with [/kiali]
2021-02-01T09:56:21Z DBG Base URL has been updated to [<base href="/kiali/"]
2021-02-01T09:56:21Z INF Generating env.js from config
2021-02-01T09:56:21Z DBG The content of /opt/kiali/console/env.js will be:
window.HISTORY_MODE='browser';
window.WEB_ROOT='/kiali';

2021-02-01T09:56:21Z INF Server endpoint will start at [:20001/kiali]
2021-02-01T09:56:21Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-02-01T09:56:21Z INF Starting Metrics Server on [:9090]


2021-02-01T09:56:41Z DBG Detected Istio version [1.8.1-806fb24bc121bf93ea06f6a38b7ccb3d78d1f326-Clean]
2021-02-01T09:56:41Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T09:56:41Z INF Kiali Cache is active for namespaces [.*]
2021-02-01T09:56:41Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T09:56:41Z INF [Prom Cache] Enabled
2021-02-01T09:56:41Z INF Waiting for Kiali cache for [namespace: istio-system] to sync
2021-02-01T09:56:41Z DBG Reducing requestedDuration [30m0s] to safeDuration [6m50s]
2021-02-01T09:56:41Z INF Kiali cache for [namespace: istio-system] started
2021-02-01T09:56:41Z INF Waiting for Kiali cache for [namespace: electronic-shop] to sync
2021-02-01T09:56:41Z INF Kiali cache for [namespace: electronic-shop] started
2021-02-01T09:56:42Z DBG Rate interval for namespace electronic-shop was adjusted to 411s (original = 1800s, query time = 2021-02-01 09:56:42.271415741 +0000 UTC m=+21.220514199, namespace created = 2021-02-01 09:49:51 +0000 UTC)
2021-02-01T09:56:42Z DBG [extractMetricsQueryParams] Requested query start time [2021-02-01 09:26:42.467194058 +0000 UTC m=-1778.583707483] set to allowed time [2021-02-01 09:52:51 +0000 UTC]
2021-02-01T09:57:03Z DBG Reducing requestedDuration [30m0s] to safeDuration [7m12s]
2021-02-01T09:57:13Z DBG Reducing requestedDuration [30m0s] to safeDuration [7m22s]
2021-02-01T09:57:16Z DBG Reducing requestedDuration [30m0s] to safeDuration [7m25s]
2021-02-01T09:57:41Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T09:57:42Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T09:57:42Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T09:57:42Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T09:58:03Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
```

**Comment by lucasponce** [comment]
Ah, I see something:

```
2021-02-01T09:56:41Z INF Kiali Cache is active for namespaces [.*]
...
2021-02-01T09:56:41Z INF Waiting for Kiali cache for [namespace: istio-system] to sync
```

In the last helm install, this shouldn't happen, I have a suspect with the caching on the excluded cni namespace.

Let me see if I missed something in the config

**Comment by lucasponce** [comment]
@MrBlaise I think we are close thanks to your help.

Another test, would you mind to add this into the ConfigMap and restart the Kiali pod (no need to re-install using helm).

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L679

Try to keep cache enabled, but only on electronic-shop namespace.

I'd like to test if the problem is with the istio-system namespace cache in general.

Thanks a lot.

In the logs it should update that.

**Comment by MrBlaise** [comment]
If I set it to electonic shop only it says this:

```
2021-02-01T10:07:38Z INF Kiali: Version: v1.29.0, Commit: a86a8fcffeb002d35fc0964dfd728958295b8387

2021-02-01T10:07:38Z DBG Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml]
2021-02-01T10:07:38Z DBG Reading YAML config from [/kiali-configuration/config.yaml]
2021-02-01T10:07:38Z INF Using authentication strategy [anonymous]
2021-02-01T10:07:38Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2021-02-01T10:07:38Z INF Kiali: Console version: 1.29.0
2021-02-01T10:07:38Z INF Updating base URL in index.html with [/kiali]
2021-02-01T10:07:38Z DBG Base URL has been updated to [<base href="/kiali/"]
2021-02-01T10:07:38Z INF Generating env.js from config
2021-02-01T10:07:38Z DBG The content of /opt/kiali/console/env.js will be:
window.HISTORY_MODE='browser';
window.WEB_ROOT='/kiali';

2021-02-01T10:07:38Z INF Server endpoint will start at [:20001/kiali]
2021-02-01T10:07:38Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-02-01T10:07:38Z INF Starting Metrics Server on [:9090]
2021-02-01T10:08:06Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T10:08:06Z INF Kiali Cache is active for namespaces [electronic-shop]
2021-02-01T10:08:06Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T10:08:06Z INF [Prom Cache] Enabled
2021-02-01T10:08:06Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:06Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:06Z DBG Reducing requestedDuration [30m0s] to safeDuration [18m15s]
2021-02-01T10:08:06Z INF Waiting for Kiali cache for [namespace: electronic-shop] to sync
2021-02-01T10:08:06Z INF Kiali cache for [namespace: electronic-shop] started
2021-02-01T10:08:06Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:06Z DBG Reducing requestedDuration [30m0s] to safeDuration [18m15s]
2021-02-01T10:08:06Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:06Z DBG Reducing requestedDuration [30m0s] to safeDuration [18m15s]
2021-02-01T10:08:07Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:07Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:07Z DBG Reducing requestedDuration [30m0s] to safeDuration [18m16s]
2021-02-01T10:08:07Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:07Z DBG Reducing requestedDuration [30m0s] to safeDuration [18m16s]
2021-02-01T10:08:07Z WRN Kiali has not [istio-system] namespace cached. It is required to fetch Istio Status correctly
2021-02-01T10:08:08Z DBG Reducing requestedDuration [30m0s] to safeDuration [18m17s]


2021-02-01T10:09:06Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:09:06Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:09:07Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:09:07Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:09:07Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:09:08Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
``

If I add istio-system in addition to electronic-shop:

```
2021-02-01T10:14:59Z INF Kiali: Version: v1.29.0, Commit: a86a8fcffeb002d35fc0964dfd728958295b8387

2021-02-01T10:14:59Z DBG Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml]
2021-02-01T10:14:59Z DBG Reading YAML config from [/kiali-configuration/config.yaml]
2021-02-01T10:14:59Z INF Using authentication strategy [anonymous]
2021-02-01T10:14:59Z WRN Kiali auth strategy is configured for anonymous access - users will not be authenticated.
2021-02-01T10:14:59Z INF Kiali: Console version: 1.29.0
2021-02-01T10:14:59Z INF Updating base URL in index.html with [/kiali]
2021-02-01T10:14:59Z DBG Base URL has been updated to [<base href="/kiali/"]
2021-02-01T10:14:59Z INF Generating env.js from config
2021-02-01T10:14:59Z DBG The content of /opt/kiali/console/env.js will be:
window.HISTORY_MODE='browser';
window.WEB_ROOT='/kiali';

2021-02-01T10:14:59Z INF Server endpoint will start at [:20001/kiali]
2021-02-01T10:14:59Z INF Server endpoint will serve static content from [/opt/kiali/console]
2021-02-01T10:14:59Z INF Starting Metrics Server on [:9090]
2021-02-01T10:15:13Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T10:15:13Z INF Kiali Cache is active for namespaces [istio-system electronic-shop]
2021-02-01T10:15:13Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T10:15:13Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T10:15:13Z DBG Rest perf config QPS: 175.000000 Burst: 200
2021-02-01T10:15:13Z INF [Prom Cache] Enabled
2021-02-01T10:15:13Z INF Waiting for Kiali cache for [namespace: istio-system] to sync
2021-02-01T10:15:13Z DBG Reducing requestedDuration [30m0s] to safeDuration [25m22s]
2021-02-01T10:15:14Z INF Kiali cache for [namespace: istio-system] started
2021-02-01T10:15:14Z INF Waiting for Kiali cache for [namespace: electronic-shop] to sync
2021-02-01T10:15:14Z INF Kiali cache for [namespace: electronic-shop] started
2021-02-01T10:15:14Z DBG Detected Istio version [1.8.1-806fb24bc121bf93ea06f6a38b7ccb3d78d1f326-Clean]
2021-02-01T10:15:16Z DBG Rate interval for namespace electronic-shop was adjusted to 1525s (original = 1800s, query time = 2021-02-01 10:15:16.012217719 +0000 UTC m=+16.519115894, namespace created = 2021-02-01 09:49:51 +0000 UTC)
2021-02-01T10:15:16Z DBG [extractMetricsQueryParams] Requested query start time [2021-02-01 09:45:16.220646942 +0000 UTC m=-1783.272454878] set to allowed time [2021-02-01 09:52:51 +0000 UTC]
2021-02-01T10:15:32Z DBG Reducing requestedDuration [30m0s] to safeDuration [25m41s]
2021-02-01T10:15:34Z DBG Reducing requestedDuration [30m0s] to safeDuration [25m43s]
2021-02-01T10:15:37Z DBG Reducing requestedDuration [30m0s] to safeDuration [25m46s]
2021-02-01T10:16:14Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:16:16Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:16:16Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:16:16Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
```

In both instances the problem is still occurring (nothing loads)

**Comment by lucasponce** [comment]
> If I set it to electonic shop only it says this (the kiali UI fails to load):

This is interesting, it will help us to chase this.
Thanks again.

I guess I have more information to review, thanks a lot, I'll add comments on new info.

**Comment by xeviknal** [comment]
@MrBlaise couple of questions:

1. do you have problems running the `istioctl proxy-status` command?
2. Could you try to fetch the proxy-status from the istiod pod? (really similar to what Kiali does)
```
kubectl port-forward -n ${ISTIO-NAMESPACE} ${ISTIOD_POD} 18080:8080
curl http://localhost:18080/debug/syncz
```

Kiali should have access to istiod pods to fetch the `/debug/syncz` endpoint. Otherwise, Kiali will fail to compute the proxy-status for each pod.

**Comment by MrBlaise** [comment]
> curl http://localhost:18080/debug/syncz



> @MrBlaise couple of questions:
> 
> 1. Do you have problems running the `istioctl proxy-status` command?
> 2. Could you try to fetch the proxy-status from the istiod pod? (really similar to what Kiali does)
> 
> ```
> kubectl port-forward -n ${ISTIO-NAMESPACE} ${ISTIOD_POD} 18080:8080
> curl http://localhost:18080/debug/syncz
> ```
> 
> Kiali should have access to istiod pods to fetch the `/debug/syncz` endpoint. Otherwise, Kiali will fail to compute the proxy-status for each pod.

@xeviknal Both `istioctl proxy-status` and curling the debug/syncz is fine.
I am guessing this functionality is required/same whether cache is enabled or not, so I don't see why would this be the cause.

**Comment by xeviknal** [comment]
@MrBlaise when disabling the cache, the `proxy-status` in health is disabled too. Plus, your logs say that the `istiod` is no able to return the proxy statuses:

```
2021-02-01T10:16:14Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:16:16Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:16:16Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
2021-02-01T10:16:16Z WRN GetPodProxyStatus is failing for [namespace: electronic-shop] [pod: bookstore-v1-5cdc7544c8-ks8vs]: the server is currently unable to handle the request (get pods istiod-674c98ddf8-5l7zt)
```

**Comment by MrBlaise** [comment]
I see @xeviknal thanks for clarifying!

However, I can access the proxy-status so this is still a mystery :/. I did check these before because I saw there was an issue with running HA istiod setup (more than 1 replica) but as I mentioned I've made sure only one replica is running while I am debugging this and that didn't help, nor I experience any other issue with istiod on its own.

**Comment by xeviknal** [comment]
Kiali 1.24 it should be the last release working (it doesn't have the proxy-status). Kiali 1.25 should present the same bug.

**Comment by MrBlaise** [comment]
> Kiali 1.24 it should be the last release working (it doesn't have the proxy-status). Kiali 1.25 should present the same bug.

I've tried 1.25 and that was not good either indeed, after that, I just stuck with 1.20. I installed 1.24 now and that is also working as you mentioned.

**Comment by lucasponce** [comment]
Thanks @MrBlaise.
In Kiali 1.25, did you enable cache ? Or it's still working without caching enabled for your env ?

**Comment by MrBlaise** [comment]
@lucasponce I've installed 1.24 because as @xeviknal mentioned that is the last version that works without turning off the caching explicitly (it has no proxy-status). So I haven't changed the caching on that one. I didn't install 1.25, rather 1.29 with caching disabled and that works too.

I'm planing to use 1.29 with caching disabled until this is figured out.

**Comment by xeviknal** [comment]
@MrBlaise @bougyman @camelpunch @JuanSeBestia @jdartigalongue @koalaty-code @kevin-shelaga @Miles-Ahead-Digital 

1. Could you guys can confirm that you use a private GKE cloud? (which version?)
2. Could you guys tell me which installation did you follow to create the private cloud? [1] (I am really new in private clusters on GKE. That might limit connections between kube control plane and istio control plane (istiod))
3. Does your kube-system pods have access to istiod pods? Kiali performs a kube proxy (and portforward) operation for each `istiod` in the cluster.

Test:
Connect to your kiali instance:
```
export KIALI_POD=$(kubectl get pod -l app=kiali -o jsonpath='{.items..metadata.name}' -n istio-system)
kubectl exec --stdin --tty ${KIALI_POD} -n istio-system -- /bin/bash
```
Inside the pod:
- Check if kiali has access to kube-api endpoints (it should)
- Check if kiali has access to the istiod endpoint (key point)

```
# Getting the bearer
KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
echo $KUBE_TOKEN

# Checking access to kube api
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/istio-system/pods

#Checking access to the pod proxy from kube-api to istiod
ISTIOD_POD_NAME=<here-your-istiod-pod-name>
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
      https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/istio-system/pods/${ISTIOD_POD_NAME}/proxy/debug/syncz
```
Thank you for your patience

[1] https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters?authuser=1#all_access

**Comment by kevin-shelaga** [comment]
@lucasponce We are running a private gke cluster 1.18.12-gke.1205, created with terraform. Though we have opened a firewall rule for api server access from components.

We obviously arent using linkerd, but the have some gcloud examples you can use, just swap in your needed ports (https://linkerd.io/2/reference/cluster-configuration/)

#Checking access to kube api
PASS

#Checking access to the pod proxy from kube-api to istiod
FAIL

```sh
[kiali@kiali-559d4884db-g9pxq kiali]$ curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
>       https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/istio-system/pods/${ISTIOD_POD_NAME}/proxy/debug/syncz
Error trying to reach service: 'dial tcp 10.91.2.15:8080: i/o timeout'
```

**Comment by lucasponce** [comment]
Thanks @kevin-shelaga, it seems that @xeviknal's suspects were in the good direction.

The mechanism to collect the proxy-status low level info from the istiod is failing in that cluster and probably is causing that problem.

@xeviknal will add more comments on this about potential next steps.

**Comment by xeviknal** [comment]
@kevin-shelaga I guess we found the problem. Thanks for confirming the suspicions.

Could you add an extra firewall rule to allow the kube api connect with the istiod on two ports:
- 8080: you'll be able to fetch the proxy status (list of envoy metadata wrt sync)
![proxy-status](https://user-images.githubusercontent.com/613814/95065068-d501ee00-0700-11eb-8be7-ecc2f1b92e70.png)
- 1500: access to envoy dump
![proxy-details](https://user-images.githubusercontent.com/613814/100870572-229b9c80-349f-11eb-8593-a2ffcb6afd91.gif)

Correct me if I am wrong, I couldn't test it because I don't have the reproducible environment, but you should run a command like this one (inspired in [istio.io](https://istio.io/latest/docs/setup/platform-setup/gke/)):

```
gcloud compute firewall-rules update <firewall-rule-name> --allow tcp:10250,tcp:443,tcp:15017,tcp:8080,tcp:15000
```

If that command is not precise enough, would you mind sharing the appropriate way to update the firewall rule? (helping the future people to fix this issue)

Thank you

**Comment by kevin-shelaga** [comment]
@lucasponce @xeviknal 

Good news, updating the firewall did the trick! About the firewall rule, GKE automatically makes firewall rules for you for tcp:10250 and tcp:443. Also if youre running istio in a private GKE cluster, you probably already have a firewall rule for tcp:15017 which is needed for sidecar injection. So all that being said the only ports I needed to open were as follows.

```sh
gcloud compute firewall-rules update <firewall-rule-name> --allow tcp:8080,tcp:15000
```

**Comment by kevin-shelaga** [comment]
Hope this saves people some time.

```sh
CLUSTER_NAME=<cluster name>

MASTER_IPV4_CIDR=$(gcloud container clusters describe $CLUSTER_NAME --project <projectID> --region <region> \
  | grep "masterIpv4CidrBlock: " \
  | awk '{print $2}')

NETWORK=$(gcloud container clusters describe $CLUSTER_NAME --project <projectID> --region <region> \
  | grep "^network: " \
  | awk '{print $2}')

NETWORK_TARGET_TAG=$(gcloud compute firewall-rules list --project <projectID> \
  --filter network=$NETWORK --format json \
  | jq ".[] | select(.name | contains(\"$CLUSTER_NAME\"))" \
  | jq -r '.targetTags[0]' | head -1)

gcloud compute firewall-rules create gke-to-istio-and-kiali \
  --project <projectID> \
  --network "$NETWORK" \
  --allow "tcp:8080,tcp:15000,tcp:15017" \
  --source-ranges "$MASTER_IPV4_CIDR" \
  --target-tags "$NETWORK_TARGET_TAG" \
  --priority 1000 \
  --description "Allow traffic on ports 8080, 15000 and 15017 for istio and kiali"
```

**Comment by xeviknal** [comment]
@kevin-shelaga beverages deserved! :cocktail:  Thank you for taking the extra time to write the instructions for feature users :clap: 

I'll definitely prepare a PR for the installation process and FAQ. And also trying to prevent this non-ending requests.

Closing the issue when the PRs are in place.

**Comment by koalaty-code** [comment]
Confirmed that updating the firewall rules to allow traffic on ports `8080` and `15000` resolved the issue with Kiali on v1.29.0. Kiali is still stable after re-enabling `kubernetes_config.cache_enabled` in our Kiali CR. We are running Kiali on a private GKE cluster 1.17.14-gke.1600.

**Comment by MrBlaise** [comment]
@xeviknal @lucasponce  @kevin-shelaga Wow thanks guys, this was a great find! It solved the problem on my clusters as well. 🎉

**Comment by JuanSeBestia** [comment]
Thanks so much, also work for me :)

**Comment by OneideLuizSchneider** [comment]
@kevin-shelaga thanks \m/
