### ISSUE TITLE
Distributed tracing view shows nested homepage

### ISSUE THREAD

**Issue by emmayang** [kiali/kiali#416]
**Describe the bug**
When configure the Kiali dashboard with latest image, and set `external_services.jaeger.url` in kiali-configmap.yaml like below : 
```
    external_services:
      jaeger:
        url: http://XXX.XXX.XXX.XX:30944
```
The "Distributed Tracing" view is not showing the jaeger UI, but showing nested homepage view.

![screen shot 2018-08-09 at 16 17 45](https://user-images.githubusercontent.com/7776218/43887244-c1f056f8-9bf0-11e8-96dc-5a08f68253ee.png)

**Versions used**
Kiali: kiali/kiali:latest
Istio: 0.8
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**
1. Deploy kiali
2. Edit `kiali-configmap.yaml` and add jaeger url 
3. Update the deployment by applying the new kiali-configmap.yaml
5. Changing back to image `kiali/kiali:v0.5.0` could fix this and all worked fine.

**Expected behavior**
Jaeger UI should be embedded other than the homepage

**Comment by pilhuhn** [comment]
On 9 Aug 2018, at 11:21, Lucas Ponce wrote:

> Could you test latest image with the istio-1.0 distribution ?

You can also try the :latest image on Dockerhub
https://hub.docker.com/r/kiali/kiali/tags/

and use it as described in 
https://medium.com/p/updating-the-kiali-version-in-your-istio-openshift-install-2fa1a618ce3a
( if you are not on OpenShift but on a different distro, then the way to 
use it may be slightly different. )

**Comment by emmayang** [comment]
@lucasponce @pilhuhn Thanks, and I did tested both Istio 0.8 and 1.0 release, and got same error. And also previous :latest image on Dockerhub would have rendering issue in `Graph` view (failed on d3 rendering I guess), and I noticed this has been fixed in latest image updated 13 hours ago.

**Comment by pilhuhn** [comment]
@emmayang Do I understand you correctly, that it is fixed (for you) and we can close the issue?

**Comment by emmayang** [comment]
@pilhuhn sorry I meat the rendering issue in `Graph` view is gone with latest image, but this `Distributed Tracing` issue is still there and not working in latest release.

**Comment by pilhuhn** [comment]
Thank you @emmayang for the clarification 👍

**Comment by lucasponce** [comment]
@emmayang with istio-1.0 ? 
Could you attach a screenshot of the "about" window in Kiali UI to check the commit used in the image and check if something is missing.

Thanks a lot

**Comment by emmayang** [comment]
@lucasponce here's the info from "about":
kiali-ui 0.6.0 (fd6bb4828830209caefe9331f42104f95e2417ae)
kiali v0.5.1-SNAPSHOT (9900da44346c11e22dff75521c843837faed3fbf)
Components
Prometheus 2.3.1
Kubernetes v1.9.9+IKS

And thanks for the information about external config! I did add it because my cluster does not have external IP, and default installation does not work for me, and popup error says it cannot find Jaeger URL. I dug around and found jaeger url can be configured there.

**Comment by lucasponce** [comment]
@emmayang thanks ! it looks the latest image you pulled has not the fix for the jaeger UI.
When a PR is merged Travis should create a new one, could you try to delete the local one you download and try to fetch the newest one ?
With the "about" info we could confirm if the fix is in place, and if it solves the issue you are seeing.

Thanks again.
Lucas

**Comment by emmayang** [comment]
@lucasponce sorry for the late reply, but I tried again and still found it not working. This time only a blank screen, and no error messages. Here's the latest version information from "about":

kiali-ui 0.6.0 (30e844162a689c0a3f9141a9711e743e0da97a6e)
kiali v0.5.1-SNAPSHOT (c97d651fcbea8e2ee84dd42256ddbaa4bfc9baed)
Components
Istio 1.0.0
Prometheus 2.3.1
Kubernetes v1.9.9+IKS

**Comment by lucasponce** [comment]
@emmayang no problem, sorry that you are still hitting the bug.
Just to confirm:
- The environment doesn't have defined any additional extra `external_services.jaeger.url` variable.
- Could you open a debug in your browser (i.e. using Chrome CTL+SHIFT+C) and check the Network tab, to see which call is failing.
- Have you access to Kiali logs ? Could you paste them ?

Also, we are in Europe TZ and available in #kiali room on Freenode, so feel free to ping us there (lponce nick), perhaps we can check if there is anything else missing.

Thanks.

**Comment by emmayang** [comment]
@lucasponce thanks always for your quick reply :-)

And I tried again and can confirm:
- yes I removed all the external_services.jaeger.url settings from `kiali-conifgmap.yaml` 
- I checked dev console for Chrome, Safari and FF (happen to be a frontend developer myself), and found no error for `http://MY_IP:MY_NODEPORT/api/jaeger`, and the response for it is `{"url":"http://MY_IP:MY_NODEPORT:32439"}`. I'm a little confused about the 2 `:` inside it, but I guess this is how the kiali-jaeger works. And btw I checked accessing the kiali-jaeger service directly by `http://MY_IP:32439`, and the jaeger UI worked fine.
- And I used `k logs -n istio-system kiali-bb9549d4f-44q4g  -f --tail=100` to check logs, and found there's no logs rolling when accessing the tracing page, and it rolls when I open "Graph" page for service graph.

And again, here's my build info:
kiali-ui 0.6.0 (595e7d600d7737184805bfa84923238fac002029)
kiali v0.5.1-SNAPSHOT (0badcf958768e87928165389cba39891df8cc816)

**Comment by lucasponce** [comment]
@emmayang thanks for the update, yeap it's seem that's the problem.
As commented in the BlueJeans session, the proxy works, but the URL which is used from Kiali is wrong.
So I will create an issue to fix this.

**Comment by lucasponce** [comment]
https://issues.jboss.org/browse/KIALI-1346

**Comment by lucasponce** [comment]
@emmayang could you fetch the latest docker kiali image and let us know if the URL is now correct.
Thanks

**Comment by pilhuhn** [comment]
Thank you @emmayang for hopping on irc (and BJ) and helping us fixing the issue!

**Comment by emmayang** [comment]
@lucasponce it worked perfectly now, really thanks for all the support! :-)

**Comment by lucasponce** [comment]
Thanks @emmayang for the feedback.
Closing this issue as resolved.

**Comment by JohnDzialo** [comment]
![screen shot 2018-08-17 at 1 59 06 pm](https://user-images.githubusercontent.com/9005145/44281432-c22cb680-a225-11e8-904f-642919807a7a.png)
This is what I see when I try to login to kiali's distributed tracing
