### ISSUE TITLE
Istio config bug

### ISSUE THREAD

**Issue by Zorgji** [kiali/kiali#6948]
### Bug brief

I'm testing Istio with gateway API and httproutes. It's all accessible and working well. But in Kiali saying as below img.
<img width="1512" alt="Screenshot 2023-12-12 at 12 20 32" src="https://github.com/kiali/kiali/assets/36134132/4830a683-0532-446d-a46f-9b7c4df79b8a">

If I put full name like `dev-grafana.monitoring.svc.cluster.local`, Istio config is fine but can't route to the App anymore.
<img width="1512" alt="Screenshot 2023-12-12 at 12 27 23" src="https://github.com/kiali/kiali/assets/36134132/94c84c9e-99f0-4de9-bf16-6536a7e16b5c">
<img width="1512" alt="Screenshot 2023-12-12 at 12 29 50" src="https://github.com/kiali/kiali/assets/36134132/f5f97fd4-845d-408a-80b2-a14e4bea43b7">

### Environment
*Currently I'm running*

- **Kiali version: v1.78.0**
- **Istio version: 1.20.0** 
- **Kubernetes version: 1.26** 
- **Other notable environmental factors: Gateway API, HTTPROUTES**

**Comment by jshaughn** [comment]
@hhovsepy Perhaps the validation here is too aggressive?

**Comment by hhovsepy** [comment]
Hi @Zorgji , in this screenshot it still shows an error message over 'dev-grafana.monitoring.svc.cluster.local' service in FQDN, does this service exist with this FQDN?

<img alt="Screenshot 2023-12-12 at 12 29 50" width="1512" src="https://private-user-images.githubusercontent.com/36134132/289702616-f5f97fd4-845d-408a-80b2-a14e4bea43b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTI2NDksIm5iZiI6MTcwMjM5MjM0OSwicGF0aCI6Ii8zNjEzNDEzMi8yODk3MDI2MTYtZjVmOTdmZDQtODQ1ZC00MDhhLTgwYjItYTE0ZTRiZWE0M2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0NDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MWJiM2QzNzcwMTdmMGQwNTAxZjdlODA3NTg1MDlkMWE3MTMyMjg0ZTFmYjVmYTkwNmExNWRkYjA3N2EyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N39hN4ayR8oNklgQ3Na_gj3PlXxQSLKR2kzLTbJf5Gc">

**Comment by Zorgji** [comment]
Hi @hhovsepy Yes yes It does exist.

**Comment by Zorgji** [comment]
@jshaughn Likely so

**Comment by hhovsepy** [comment]
@Zorgji thanks you, I think I need more info to reproduce the issue.
Validations take `name` of the service set in Istio config and convert it to FQDN ( if it is not set as FQDN ), using the namespace of config itself. Then always comparing that FQDN with the Services from Istio Service Registry.
The shown error can happen if:
1. Service with this name does not exist, or Service is in different namespace than the Istio config. For instance `dev-grafana` Service is not in `monitoring` but in `istio-system` namespace.
2. Service exists but is exported to different namespace, or exported to "~" which means invisible.
3. Istio Service Registry is not started, then there will be Error in Kiali logs and many other Errors in UI validations.
If non of the above is the case, I need the steps you used to deploy `dev-grafana`.

**Comment by Zorgji** [comment]
@hhovsepy  Thanks for clarifying  🙏
For above deployment, I've 3 ns `gateway-api`, `monitoring`, `istio-system`
1. svc `dev-grafana` exists in `monitoring` ns
2. httproutes also in the same ns `monitoring` not exported to other ns
3. not really sure about istio registry but It routes to the correct svc. I mean I can access grafana dashboard for example
---
Now I redeploy all in `istio-system` ns a new Gateway API (with istio gc) and a `httproutes` to access kiali.
All going well, but still the same if I set svc I can access this below pic, validation still showing error.
<img width="1511" alt="Screenshot 2023-12-13 at 22 28 37" src="https://github.com/kiali/kiali/assets/36134132/f3fefc00-28f6-40a0-98ab-0e7ff85ce9ff">
If I put FQDN, it's all gone and `httproutes` complained "serviceName invalid; the name of the Service must be used, not the hostname." I'm quite sure validation will be fine like above scenario. But couldn't access anymore

**Comment by hhovsepy** [comment]
Thank you @Zorgji, you are right, the issue is in validations.
I will make a fix.

**Comment by Zorgji** [comment]
Thanks man @hhovsepy really appreciate it  🙏

**Comment by hhovsepy** [comment]
@Zorgji can I ask you to check what is the value set in Kiali configmap or CR for property `istio_identity_domain`? It should be 'svc.cluster.local'.
Because in your screenshot you set value `kiali` for service name and it still shows error.

**Comment by Zorgji** [comment]
@hhovsepy In `httproute` you have to set its `svc` name to reference. didn't see that `istio_identity_domain` flag in configmap. And I don't think it's related.

**Comment by Zorgji** [comment]
To be more clear, I didn't use `istio gateway` and `virtual service`. I'm using `Gateway API` with Istio `GatewayClass` and `httproutes`. Everything is working, except showing that validation error. that's it.

**Comment by hhovsepy** [comment]
I was able to reproduce and fix the second part of the issue, when Kiali accepts FQDN as a Service name.
But the initial issue when Service 'kiali' set as a service name is showing error I cannot see:
![Screenshot from 2023-12-14 08-57-17](https://github.com/kiali/kiali/assets/604313/f8ad6936-d69e-427b-821f-eeeecf751cb3)

**Comment by Zorgji** [comment]
nice! which image tag I need to use?

**Comment by hhovsepy** [comment]
@Zorgji I mean the issue is fixed partially, and the fix will be available on upcoming Kiali v1.79 in 6 weeks. 
However the error message when you set `kiali` or `dev-grafana` as a service name, I was not able to reproduce on my environment with Istio 1.20 and Kiali 1.78 or latest, it appears only in the case when I set the `istio_identity_domain:` in Kiali configmap with 
empty ` ` value or something different than `svc.cluster.local`.
BTW the validation errors can be ignored by setting property in Kiali configmap: 
```
  validations:
    ignore: ["KIA1201", "KIA1401"]
```

**Comment by Zorgji** [comment]
Thanks man @hhovsepy Now I put the `istio_identity_domain` error is still showing, if I set validation ignore like you said error is gone.
